org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_mappings_version=[VERSIONED]
parchment_mappings_mc_version=[VERSIONED]
minecraft_version_range=[VERSIONED]
neo_version=[VERSIONED]
loader_version_range=[1,)
mod_id=oxidizable_copper_gear
mod_name=Oxidizable Copper Gear
mod_license=MIT
mod_version=1.1.1
mod_group_id=me.pajic.oxidizable_copper_gear
mod_authors=pajic, Moonkey
mod_description=Adds oxidation and waxing mechanics to copper tools and armor