org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=oxidizable_copper_gear
mod.name=Oxidizable Copper Gear
mod.group=me.pajic
mod.version=1.2.0
mod.channel_tag=
mod.authors=pajic, Moonkey
mod.contributors=
mod.license=MIT
mod.description=Adds oxidation and waxing mechanics to copper tools and armor
mod.sources_url=https://github.com/pajicadvance/oxidizable-copper-gear
mod.homepage_url=https://modrinth.com/mod/oxidizable-copper-gear
mod.issues_url=https://github.com/pajicadvance/oxidizable-copper-gear/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.parchment=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=sb4B6v2K
publish.curseforge=1349654
publish.github=false
